### ISSUE TITLE
CVAT new UI: add arrows on a mouse cursor

### ISSUE THREAD

**Issue by aschernov** [opencv/cvat#1440]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

When we change  an objects' size it will be better to see that the corresponding area is captured like in the previous ui:
![3](https://user-images.githubusercontent.com/45849884/79839403-24f03100-83bd-11ea-89a9-fbc13eecac56.gif)
The mouse cursor changes into arrows
### Current Behaviour

In new UI points highlight but it isn't enough to notice that pressing on them you can change an object's size.
![4](https://user-images.githubusercontent.com/45849884/79840021-fd4d9880-83bd-11ea-9c65-919de727cb83.gif)

### Possible Solution

Add arrows

**Comment by nmanovic** [comment]
@O

**Comment by nmanovic** [comment]
@TOsmanov , please check that it is fixed.

**Comment by aschernov** [comment]
@nmanovic ,checked. The behavior is still the same:
![mouse_arrows](https://user-images.githubusercontent.com/45849884/80375178-88d49700-88a0-11ea-88c8-1c5071297a8d.gif)

**Comment by azhavoro** [comment]
@aschernov I think this fix is not installed on our server yet, I'll update the server today, lets check tomorrow.

**Comment by TOsmanov** [comment]
@nmanovic , problem resolved
