### ISSUE TITLE
Ability to send new verification email

### ISSUE THREAD

**Issue by AndrewTKent** [opencv/cvat#4820]
### Email Issue
- I was setting up a new work email, and when I went to make a CVAT account with that email the verification email was lost. I am unable to request a new verification email and I need to use that email for work purposes. I am able to change my password for that associated account - but when I then go to login using that newly changed password it says I cant login because I haven't verified my account. 

### Possible Solution
Allow users to have another verification email sent.

**Comment by nmanovic** [comment]
@azhavoro , could you please look into the issue?

@AndrewTKent , I have checked. You are an active user. Could you please try again to reset your password?

**Comment by AndrewTKent** [comment]
@nmanovic @azhavoro I just reset my email, but I got the same error which I'll attach below. Thanks for looking into this so quickly. 

<img width="774" alt="Screen Shot 2022-08-24 at 9 32 21 AM" src="https://user-images.githubusercontent.com/57512897/186431720-23342e78-60d3-422b-a420-7c1e2cdb7da2.png">

**Comment by azhavoro** [comment]
@AndrewTKent
Please use app.cvat.ai instead of cvat.org:
![image](https://user-images.githubusercontent.com/41117609/186458244-4cfa97e3-5ef2-4956-b699-9e8a95a978b4.png)

Do you have any data on cvat.org that you would like to access?

So it's not actually a bug because you don't verify your email address on cvat.org and there's currently no way to resend a new one.

**Comment by Marishka17** [comment]
Has been fixed in #5147

**Comment by younheech** [comment]
As of today, I am still getting 
![image](https://github.com/opencv/cvat/assets/136115439/1f1af543-84b9-438f-86f1-8421eca01d84)
and not getting the confirmation email nor the password reset link
