### ISSUE TITLE
"Issue" model is incorrect

### ISSUE THREAD

**Issue by yasakova-anastasia** [opencv/cvat#4858]
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Current Behaviour

[`IssueWriteSerializer`](https://github.com/cvat-ai/cvat/blob/182c39aa8f3bf2aeaffdd5fb2a453da3bdf72240/cvat/apps/engine/serializers.py):
- has the `message` field that references the `Issue` model, but this model doesn't have such field
- has the `create()` method, which creates a comment from the `message` passed on issue creation, but there is no `update` method, which could allow to modify the `message` field in the input data of the `issue` PATCH method
- it seems wrong to create a comment for the issue message, probably, it should be redesigned

### Steps to Reproduce (for bugs)

1.
1.
1.
1.

### Your Environment

- Git hash commit (`git log -1`): `182c39aa8f3bf2aeaffdd5fb2a453da3bdf72240`
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

Issue by @zhiltsov-max

**Comment by nmanovic** [comment]
@zhiltsov-max , it should be fixed during REST API redesign.

**Comment by jarpoole** [comment]
The `message` field is still not included in the issue as far as I can tell
